export function AnnouncementDTO(announcement : any, pictures : any){
    return {
        announcement: {
            adress: announcement["adress"],
            owner: announcement["owner"],
            price: announcement["price"],
            status: announcement["status"],
            id_announcement: announcement["id_announcement"],
            num_banheiros: announcement["num_banheiros"],
            num_garage_space: announcement["num_garage_space"],
            num_rooms: announcement["num_rooms"],
            area: announcement["area"],
        },
        details: {
            box_blindex: announcement["box_blindex"],
            closet: announcement["closet"],
            american_kitchen: announcement["american_kitchen"],
            intercom: announcement["intercom"],
            furnished: announcement["furnished"],
            gourmet_balcony: announcement["gourmet_balcony"],
            balcony: announcement["balcony"],
            games_room: announcement["games_room"],
            pcd_access: announcement["pcd_access"],
            bicycle_rack: announcement["bicycle_rack"],
            coworker: announcement["coworker"],
            elevator: announcement["elevator"],
            laundry: announcement["laundry"],
            reception: announcement["reception"],
            turkish_bath:announcement["turkish_bath"],
            in_plan: announcement["in_plan"],
            in_built: announcement["in_built"],
            done: announcement["done"],
            accept_animals: announcement["accept_animals"],
            service_room: announcement["service_room"],
            closet_in_bedroom: announcement["closet_in_bedroom"],
            cabinet_in_bathroom: announcement["cabinet_in_bathroom"],
            cabinet_in_kitchen: announcement["cabinet_in_kitchen"],
            gym: announcement["gym"],
            grill: announcement["grill"],
            gourmet_space: announcement["gourmet_space"],
            green_space: announcement["green_space"],
            garden: announcement["garden"],
            pool: announcement["pool"],
            playground: announcement["playground"],
            multisports_court: announcement["multisports_court"],
            party_room: announcement["party_room"],
            big_windows: announcement["big_windows"],
            tv: announcement["tv"]
        },
        pictures: pictures
    }
}